# Generated by Django 4.2.11 on 2026-04-10

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_agent_editing_and_provider_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('delegate', 'Delegar'), ('review', 'Revisar'), ('escalate', 'Escalar'), ('context_sync', 'Sincronizar Contexto'), ('result', 'Resultado')], default='delegate', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('delivered', 'Entregue'), ('acknowledged', 'Reconhecida'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('from_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='api.agent')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='api.agentmessage')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_messages', to='api.task')),
                ('to_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='api.agent')),
            ],
            options={
                'verbose_name': 'Mensagem de Agente',
                'verbose_name_plural': 'Mensagens de Agente',
                'ordering': ['-created_at'],
            },
        ),
    ]
